site_name: Learning Bioinformatics

site_description: A comprehensive guide to learning Bioinformatics




site_author: Teach Me Codes
site_url: https://learning.teachme.codes
site_language: en

repo_url: https://github.com/teach-me-codes/bioinformatics

extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js



markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni




  
theme:
  name: 'material'
  #custom_dir: overrides
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
# Plugins
  plugins:
    - blog
    - search:
        separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - minify:
        minify_html: true
  
   
 
#extra_css:
#  - extra.css


extra:
  analytics:
    provider: google
    property: G-ECS7B3X8JM
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback!
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >- 
          Thanks for your feedback! Help us improve this page by
          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://teach-me-codes.github.io
    - icon: fontawesome/brands/twitter
      link: https://x.com/TeachMeCodes
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/teachmecodes
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/teach-me-codes
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@teach-me-codes



nav:
- Introduction to Bioinformatics: introduction_to_bioinformatics.md
- Sequence Alignment: sequence_alignment.md
- Genome Assembly: genome_assembly.md
- Gene Prediction: gene_prediction.md
- Protein Structure Prediction: protein_structure_prediction.md
- Molecular Docking: molecular_docking.md
- Phylogenetic Analysis: phylogenetic_analysis.md
- Functional Genomics: functional_genomics.md
- Transcriptomics: transcriptomics.md
- Metagenomics: metagenomics.md
- Introduction to Genomics: introduction_to_genomics.md
- Whole Genome Sequencing: whole_genome_sequencing.md
- Exome Sequencing: exome_sequencing.md
- Genome-Wide Association Studies: genome_wide_association_studies.md
- Comparative Genomics: comparative_genomics.md
- Epigenomics: epigenomics.md
- Structural Genomics: structural_genomics.md
- Functional Annotation: functional_annotation.md
- Introduction to Omics: introduction_to_omics.md
- Proteomics: proteomics.md
- Metabolomics: metabolomics.md
- Lipidomics: lipidomics.md
- Glycomics: glycomics.md
- Pharmacogenomics: pharmacogenomics.md
- Nutrigenomics: nutrigenomics.md
- Epitranscriptomics: epitranscriptomics.md
- Single-cell Omics: single_cell_omics.md
- Microbiomics: microbiomics.md
- Interactomics: interactomics.md
- Data Integration: data_integration.md
- Data Visualization: data_visualization.md
- Machine Learning in Bioinformatics: machine_learning_in_bioinformatics.md
- Population Genomics: population_genomics.md
- Clinical Genomics: clinical_genomics.md
- Toxicogenomics: toxicogenomics.md
- Immunogenomics: immunogenomics.md
- Systems Biology: systems_biology.md
- Cancer Genomics: cancer_genomics.md

